### ISSUE TITLE
Text Preprocessing

### ISSUE THREAD

**Issue by cschubert29** [cschubert29/AppleSA#2]
- [x] JSON to dataframe
- [x] Preprocessing functions
- [x] Handling retweets and quote tweets - (quote tweets have an added comment to original tweet vs retweets are re-posting another tweet exactly as it was)
- [x] **Out of Scope** - Handling threads - search for instances where the in_reply_to_user_id and author user_id are equal
- [x] Tokenization

- [x] hashtags - terms separated by semicolons

**Comment by dreygar23** [comment]
**Threads**: I was going over my Lit Review and I mentioned the issue of threaded tweets. I was not going to handle threads. I was going to treat every tweet as a single utterance. So threads are out of the scope of my initial project proposal. We can work on them should we have time but I do not think we should focus on that for too long, I doubt this is going to be too common. 

**Retweets & Quotes**: Retweets should be discarded only if original tweet is in corpus. Only the additional text should be extracted from a quoted tweet.

**Comment by cschubert29** [comment]
All to-do items have been completed. However, hashtags in the form of #sundayfootball become sundayfootball; and not sunday football;
Only hashtags which contain multiple words capitalized get split up: #SundayFootball => Sunday Football;
I can work on a hashtag splitter that handles this but it would have to result in multiple answers due to the ambiguity.

**Comment by dreygar23** [comment]
Preprocessing issues to revisit:

- [x] 1. Key words such as iPhone in main tweet text are being split into "i phone" causing issues with POS tagging (i/PRP phone/NN vs. iphone/NNP). Please see list of words to exclude from hashtag split below (I believe this is everything on the Apple product list): 

        Iphone, Ipad, IOS, IWatch, MacBook, AppleTV, Ipod, AirPods, IMac, AppleWatch

- [x] 2. Some aspects of dependency parsing and NER are case sensitive, making a tweet that is all lower-case difficult to decipher.  May need to remove tweets that consists of only hashtags (#apple #love #best #phone #ever) or single word tweets (gross!).  

- [x] 3. Hashtag handling may need to be revisited. 
- Those hashtags that are embedded in a sentence would need to be handled differently than hashtags outside of main tweet text. For example in "my new #iphone just died! #apple#sucks" iphone should become part of the sentence as a word while #apple#sucks should be differentiated as hashtags. Not exactly sure if these hashtags should just be omitted from sentence completely or differentiated in a way that they are unmistakably hashtags (the semicolon isn't working as well as I'd hoped) 
- Hashtags that are key words (we may need to predefine these) should not be split using criteria in comment above as this affects POS tagging as described in number 1.
